import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "next-env.d.ts",
    // PWA Workbox output (generated by `npm run build`)
    "public/sw.js",
    "public/workbox-*.js",
    ".storybook/**",
    "src/**/*.stories.ts",
    "src/**/*.stories.tsx",
  ]),
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: [
      "src/legacy/**",
      "src/**/__tests__/**",
      "src/**/*edge-cases.test.ts",
      "src/**/*edge-cases.test.tsx",
      "src/lib/worker.ts",
      "src/lib/worker-manager.ts",
      "src/lib/monitoring.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/scoring/scoring-model",
              message: "Import from @/scoring instead.",
            },
          ],
        },
      ],
    },
  },
  {
    files: [
      "src/**/*.test.ts",
      "src/**/*.test.tsx",
      "src/**/__tests__/**/*.ts",
      "src/**/__tests__/**/*.tsx",
      "src/**/*edge-cases.test.ts",
      "src/**/*edge-cases.test.tsx",
      ".storybook/**/*.ts",
      ".storybook/**/*.tsx",
      "src/lib/worker.ts",
      "src/lib/worker-manager.ts",
      "src/lib/monitoring.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
]);

export default eslintConfig;
