#!/bin/bash

# PCMS One-Command Setup Script
# For macOS (including MacBook Air M4)

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Helper functions
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running on macOS
check_macos() {
    if [[ "$OSTYPE" != "darwin"* ]]; then
        print_error "This script is designed for macOS. Current OS: $OSTYPE"
        exit 1
    fi
    print_success "macOS detected"
}

# Check if Homebrew is installed
check_homebrew() {
    if ! command -v brew &> /dev/null; then
        print_status "Installing Homebrew..."
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
        # Add Homebrew to PATH for Apple Silicon Macs
        if [[ $(uname -m) == "arm64" ]]; then
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
            eval "$(/opt/homebrew/bin/brew shellenv)"
        fi
    else
        print_success "Homebrew is already installed"
    fi
}

# Install Node.js if not present
check_nodejs() {
    if ! command -v node &> /dev/null; then
        print_status "Installing Node.js..."
        brew install node
    else
        NODE_VERSION=$(node --version | cut -d'v' -f2 | cut -d'.' -f1)
        if [[ $NODE_VERSION -lt 18 ]]; then
            print_warning "Node.js version $NODE_VERSION detected. Updating to v18+..."
            brew upgrade node
        else
            print_success "Node.js $(node --version) is installed"
        fi
    fi
}

# Check for npm
check_npm() {
    if ! command -v npm &> /dev/null; then
        print_error "npm not found. Please install Node.js first."
        exit 1
    fi
    print_success "npm $(npm --version) is installed"
}

# Install dependencies
install_dependencies() {
    print_status "Installing project dependencies..."
    npm install
    print_success "Dependencies installed"
}

# Create environment file
setup_environment() {
    if [ ! -f ".env.local" ]; then
        print_status "Creating environment file..."
        
        cat > .env.local << EOF
# PCMS Environment Configuration
# Generated by setup script on $(date)

# Supabase Configuration (required for data collection)
# Create a free account at https://supabase.com
NEXT_PUBLIC_SUPABASE_URL=your_supabase_project_url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key

# Development settings
NODE_ENV=development

# Optional: Enable debug mode
DEBUG=false
EOF
        
        print_warning "Environment file created. Please edit .env.local with your Supabase credentials."
        print_status "To get Supabase credentials:"
        print_status "1. Visit https://supabase.com and create a new project"
        print_status "2. Go to Settings > API"
        print_status "3. Copy the Project URL and anon key"
        print_status "4. Update .env.local with these values"
    else
        print_success "Environment file already exists"
    fi
}

# Setup database (optional)
setup_database() {
    print_status "Database setup instructions:"
    print_status "1. Open your Supabase project dashboard"
    print_status "2. Go to the SQL Editor"
    print_status "3. Copy and run the contents of supabase-schema.sql"
    print_status "4. This will create the necessary tables for data collection"
    print_warning "Skip this step if you want to run the system without data collection"
}

# Build the project
build_project() {
    print_status "Building the project..."
    npm run build
    print_success "Project built successfully"
}

# Start the development server
start_server() {
    print_status "Starting the development server..."
    print_success "PCMS will be available at http://localhost:3000"
    print_warning "Press Ctrl+C to stop the server or run './setup.sh stop'"
    npm run dev
}

# Stop the development server
stop_server() {
    print_status "Stopping development server..."
    
    # Find and kill Node.js processes using port 3000
    local pid=$(lsof -ti:3000 2>/dev/null || true)
    if [ -n "$pid" ]; then
        kill -TERM $pid 2>/dev/null || true
        sleep 2
        
        # Force kill if still running
        if kill -0 $pid 2>/dev/null 2>/dev/null; then
            kill -KILL $pid 2>/dev/null || true
        fi
        
        print_success "Development server stopped"
    else
        print_warning "No development server found running on port 3000"
    fi
    
    # Also kill any remaining Next.js processes
    pkill -f "next dev" 2>/dev/null || true
    pkill -f "node.*next" 2>/dev/null || true
}

# Clean up local data
cleanup_local_data() {
    print_status "Cleaning up local data..."
    
    # Clear browser localStorage (instructions for user)
    print_warning "To clear browser data:"
    print_status "1. Open http://localhost:3000 in your browser"
    print_status "2. Open Developer Tools (Cmd+Option+I)"
    print_status "3. Go to Application > Local Storage"
    print_status "4. Right-click and Clear Storage"
    
    # Clear any local cache files
    if [ -d ".next" ]; then
        rm -rf .next
        print_status "Cleared Next.js cache"
    fi
    
    if [ -d "node_modules/.cache" ]; then
        rm -rf node_modules/.cache
        print_status "Cleared npm cache"
    fi
}

# Verify ignored-artifact safety before commit.
run_verify() {
    if [ ! -x "./verify-gitignore.sh" ]; then
        print_error "verify-gitignore.sh is missing or not executable."
        exit 1
    fi
    ./verify-gitignore.sh
}

# Update dependencies
update_dependencies() {
    print_status "Updating dependencies..."
    
    # Update npm to latest
    npm install -g npm@latest
    
    # Update project dependencies
    npm update
    
    # Check for outdated packages
    print_status "Checking for outdated packages..."
    npm outdated
    
    print_success "Dependencies updated"
    print_warning "Review the outdated packages list above and update manually if needed"
}

# Remove project completely
remove_project() {
    print_warning "This will completely remove the PCMS project from your system."
    print_warning "All local data, dependencies, and configuration will be deleted."
    
    read -p "Are you sure you want to continue? (type 'REMOVE' to confirm): " -r
    if [[ $REPLY != "REMOVE" ]]; then
        print_status "Removal cancelled."
        return
    fi
    
    print_status "Removing PCMS project..."
    
    # Stop any running servers
    stop_server
    
    # Remove all project files
    cd ..
    rm -rf perceptual-cognitive-mapping-system
    
    print_success "PCMS project completely removed from your system"
    print_warning "If you set up Supabase, you may want to clean up your Supabase project as well"
}

# Reset project to clean state
reset_project() {
    print_warning "This will reset the project to a clean state (keeps source code)."
    
    read -p "Continue with reset? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_status "Reset cancelled."
        return
    fi
    
    print_status "Resetting project..."
    
    # Stop server
    stop_server
    
    # Clean build artifacts
    npm run clean 2>/dev/null || rm -rf .next dist
    
    # Reset dependencies
    rm -rf node_modules package-lock.json
    
    # Clean local data
    cleanup_local_data
    
    # Reinstall dependencies
    install_dependencies
    
    print_success "Project reset to clean state"
}

# Show usage information
show_usage() {
    echo "PCMS Setup Script - Perceptual & Cognitive Mapping System"
    echo ""
    echo "Usage: $0 [COMMAND]"
    echo ""
    echo "Commands:"
    echo "  setup      - Complete setup (default)"
    echo "  start      - Start development server"
    echo "  stop       - Stop development server"
    echo "  restart    - Restart development server"
    echo "  clean      - Clean local data and cache"
    echo "  update     - Update dependencies"
    echo "  reset      - Reset to clean state"
    echo "  remove     - Remove project completely"
    echo "  status     - Show system status"
    echo "  verify     - Verify ignored/staged artifact safety"
    echo "  help       - Show this help"
    echo ""
    echo "Examples:"
    echo "  $0              # Run full setup"
    echo "  $0 start        # Start server"
    echo "  $0 stop         # Stop server"
    echo "  $0 clean        # Clean local data"
    echo "  $0 verify       # Verify ignored/staged artifacts"
    echo "  $0 remove       # Remove everything"
}

# Show system status
show_status() {
    echo "=========================================="
    echo "  PCMS System Status"
    echo "=========================================="
    echo ""
    
    # Check if server is running
    local pid=$(lsof -ti:3000 2>/dev/null || true)
    if [ -n "$pid" ]; then
        print_success "Development server is running (PID: $pid)"
        print_status "Available at: http://localhost:3000"
    else
        print_warning "Development server is not running"
    fi
    
    echo ""
    
    # Check dependencies
    if command -v node &> /dev/null; then
        print_success "Node.js: $(node --version)"
    else
        print_error "Node.js: Not installed"
    fi
    
    if command -v npm &> /dev/null; then
        print_success "npm: $(npm --version)"
    else
        print_error "npm: Not installed"
    fi
    
    echo ""
    
    # Check project structure
    if [ -f "package.json" ]; then
        print_success "Project structure: OK"
    else
        print_error "Project structure: Not found"
    fi
    
    if [ -d "node_modules" ]; then
        print_success "Dependencies: Installed"
    else
        print_warning "Dependencies: Not installed"
    fi
    
    if [ -f ".env.local" ]; then
        print_success "Environment: Configured"
    else
        print_warning "Environment: Not configured"
    fi
    
    echo ""
}

# Main function with command handling
main() {
    local command=${1:-setup}
    
    case $command in
        "setup")
            echo "=========================================="
            echo "  PCMS One-Command Setup Script"
            echo "  Perceptual & Cognitive Mapping System"
            echo "=========================================="
            echo ""
            
            print_status "Starting PCMS setup for macOS..."
            echo ""
            
            # Check system requirements
            check_macos
            check_homebrew
            check_nodejs
            check_npm
            
            echo ""
            
            # Install project dependencies
            install_dependencies
            
            echo ""
            
            # Setup environment
            setup_environment
            
            echo ""
            
            # Database setup instructions
            setup_database
            
            echo ""
            
            # Build project
            build_project
            
            echo ""
            echo "=========================================="
            print_success "PCMS setup completed successfully!"
            echo "=========================================="
            echo ""
            print_status "Next steps:"
            print_status "1. Edit .env.local with your Supabase credentials (optional)"
            print_status "2. Run './setup.sh start' to start the development server"
            print_status "3. Open http://localhost:3000 in your browser"
            print_status "4. Complete the assessment to test the system"
            echo ""
            print_status "Available commands:"
            print_status "./setup.sh start    # Start server"
            print_status "./setup.sh stop     # Stop server"
            print_status "./setup.sh status   # Check status"
            print_status "./setup.sh clean    # Clean data"
            print_status "./setup.sh remove   # Remove everything"
            echo ""
            print_status "For full documentation, see README.md"
            echo ""
            
            # Ask if user wants to start the server
            read -p "Do you want to start the development server now? (y/n): " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                start_server
            else
                print_status "To start the server later, run: ./setup.sh start"
            fi
            ;;
            
        "start")
            start_server
            ;;
            
        "stop")
            stop_server
            ;;
            
        "restart")
            print_status "Restarting development server..."
            stop_server
            sleep 2
            start_server
            ;;
            
        "clean")
            cleanup_local_data
            ;;
            
        "update")
            update_dependencies
            ;;
            
        "reset")
            reset_project
            ;;
            
        "remove")
            remove_project
            ;;
            
        "status")
            show_status
            ;;

        "verify")
            run_verify
            ;;
            
        "help"|"-h"|"--help")
            show_usage
            ;;
            
        *)
            print_error "Unknown command: $command"
            echo ""
            show_usage
            exit 1
            ;;
    esac
}

# Handle script interruption
trap 'print_warning "Setup interrupted. Run the script again to complete setup."' INT

# Run main function
main "$@"
