/**
 * Behavioral, situational stems: short lines, everyday non-WEIRD settings, suitable for audio.
 * Reverse flags are applied when building the bank (mixed ~50% per construct).
 */
import type { EightConstructId } from '../src/model/eight-constructs';

export type StemRow = { construct: EightConstructId; text: string; reverse: boolean };

/** 25 stems per construct; reverse is assigned in the generator for ≥2 per construct. */
export const STEM_TEXT: Record<EightConstructId, readonly string[]> = {
  predictability_adaptivity: [
    'When the order of the day changes suddenly, I still feel steady inside.',
    'I like to know early what kind of work or tasks are coming.',
    'If plans fall apart, I can shift without feeling lost for long.',
    'When others change the time we agreed on, I need a moment to reset.',
    'A clear sense of what happens next helps my body feel settled.',
    'Surprise visits or sudden news rarely throw me off for the whole day.',
    'When the path I take is unknown, I move forward anyway.',
    'I feel better when the steps ahead are spelled out simply.',
    'If rules for a shared task shift mid-way, I adapt without much fuss.',
    'When nothing is fixed in advance, I can still find a rhythm.',
    'Knowing roughly when rest and food will come makes the day easier.',
    'Sudden loud announcements in a crowd do not ruin my whole plan.',
    'If someone takes a different route than we said, I adjust quickly.',
    'When timing slips, I can wait without my mind spinning.',
    'I prefer small routines I can count on, even when life is busy.',
    'When the weather turns and work must change, I accept it calmly.',
    'If a tool breaks, I can switch to another way without panic.',
    'When many small things go wrong at once, I look for one simple next step.',
    'I like agreements about who does what before we start a shared job.',
    'When the group changes the plan, I ask once, then go along.',
    'If I must leave home without knowing return time, I feel uneasy.',
    'When the day is wide open, I still pick one small anchor task.',
    'Surprise gifts or visits feel fine even if I did not prepare.',
    'When travel delays happen, I find a place to sit and breathe.',
    'If instructions come late, I can still begin with what I know.',
  ],
  sensory_processing: [
    'Bright midday light on my face can feel tiring after a while.',
    'Many overlapping voices make it harder for me to track one line of talk.',
    'Rough fabric on my skin can distract me until I adjust it.',
    'Strong smells nearby pull my attention even when I try to focus elsewhere.',
    'Quiet evenings feel easier on my nerves than noisy gatherings.',
    'When feet are wet for a long time, the feeling stays in my mind.',
    'Sudden sharp sounds make my body tense before I think.',
    'Crowded rooms with close bodies feel draining after some minutes.',
    'Gentle wind on skin usually feels pleasant, not irritating.',
    'When music is very loud, I step back or cover my ears.',
    'Dim light helps my eyes relax when I have been outside all day.',
    'Sticky hands after cooking distract me until I wash them.',
    'When dogs bark close by, I notice it before other sounds.',
    'Soft blankets help me settle when I try to rest.',
    'When many colors and signs compete, I scan slowly to find my way.',
    'Heat that builds in a closed space makes it hard to think clearly.',
    'Cold water on my face wakes me up fast.',
    'When footsteps echo in a hall, I track the rhythm without trying.',
    'Bright phone screens at night feel harsh on my eyes.',
    'When cooking smoke drifts toward me, I move or open air.',
    'Rain on a roof can soothe me until I sleep.',
    'When a baby cries nearby, I notice it before other tasks.',
    'Sand or grit inside shoes bothers me until I clear it.',
    'When a room is too still and silent, I may seek a little sound.',
    'Humming a tune helps me carry a heavy load farther.',
  ],
  cognitive_framing: [
    'I notice repeating shapes or rhythms in what others treat as random.',
    'When learning something new, I look for one simple picture in my mind.',
    'I spot when two stories people tell do not match.',
    'Breaking a big job into small named parts helps me begin.',
    'When someone gives only words, I ask for a quick sketch or gesture.',
    'I compare today with yesterday to see what really changed.',
    'If a problem looks like one I saw before, I reuse what worked.',
    'When facts clash, I hold both in mind until a pattern appears.',
    'I like naming the main risk before we act as a group.',
    'When directions confuse me, I walk a short test path first.',
    'I see links between chores that others keep separate.',
    'If a rule feels unclear, I try one harmless example to learn.',
    'When listening to a long talk, I mark two ideas to remember.',
    'I turn a messy list into a circle or line in my head.',
    'When someone jumps topics fast, I ask which one matters now.',
    'I notice when a story grows bigger each time it is retold.',
    'If a tool can serve two jobs, I prefer that over carrying more.',
    'When counting stock or harvest, I group items to avoid mistakes.',
    'I scan the horizon for landmarks before crossing open land.',
    'When teaching a child, I show once with hands, then with words.',
    'If numbers feel abstract, I picture piles or rows.',
    'When two people disagree, I restate what each wants in plain words.',
    'I like a short summary at the end of a meeting.',
    'When maps are missing, I draw a rough one in dirt or paper.',
    'If a joke hides an insult, I name the hurt plainly.',
  ],
  social_orientation: [
    'After a long day with many people, I seek quiet to recharge.',
    'Working side by side in silence feels comfortable with the right person.',
    'I step forward when a group needs someone to speak plainly.',
    'When newcomers arrive, I greet them before returning to work.',
    'I listen longer when someone seems shaken by news.',
    'Large feasts with many tables lift my mood if I know a few faces.',
    'When conflict rises, I try to lower voices before solving facts.',
    'I enjoy short jokes that do not shame anyone.',
    'If someone is left out of a task, I invite them in.',
    'When I am tired, I still nod to neighbors I pass.',
    'I share food when someone nearby looks hungry.',
    'When a child clings to a parent, I give space and a smile.',
    'I prefer small circles for deep talk over big crowds for shallow chat.',
    'When praise is due, I say it soon rather than waiting.',
    'If gossip starts, I change the subject to something useful.',
    'When elders speak, I wait for a pause before answering.',
    'I feel responsible to warn others about a loose step or sharp nail.',
    'When music starts, I may clap even if I do not dance.',
    'If someone apologizes, I accept without dragging the past.',
    'When teamwork stalls, I offer one concrete task I can take.',
    'I remember faces faster than written names.',
    'When someone is shamed in public, I feel heat in my chest.',
    'I step back when two leaders argue; I wait for a signal.',
    'When a friend is sick, I visit with something small to eat.',
    'If a stranger needs directions, I walk them to a clear landmark.',
  ],
  information_load: [
    'When many people talk at once, I pick one voice and stay with it.',
    'If too many tasks land at the same hour, I freeze for a moment.',
    'I write marks on my hand when I must remember numbers briefly.',
    'When instructions come fast, I ask for the first step again.',
    'A short list of three jobs feels easier than a long speech.',
    'When noise rises, I repeat the new fact under my breath.',
    'If someone adds detail after detail, I ask what matters today.',
    'When carrying water and watching children, I drop one task in my mind.',
    'I slow down on purpose when a message feels heavy.',
    'When two radios play, I cannot track either story well.',
    'If a line of numbers grows, I group them in pairs to check.',
    'When news arrives in fragments, I wait before I repeat it.',
    'I set one object in a special place to mean “remember this.”',
    'When teaching, I show one example, then pause.',
    'If my mind feels full, I sit and drink before deciding.',
    'When many signs point different ways, I ask a local person once.',
    'I drop low-priority jobs when time is short.',
    'When counting money, I speak the amount aloud softly.',
    'If a story has too many names, I focus on the outcome only.',
    'When packing for travel, I lay items out before closing the bag.',
    'I repeat a new name three times when I first hear it.',
    'When machines beep often, I mute what I can.',
    'If a crowd asks questions together, I raise one finger for order.',
    'When reading is hard, I listen instead if someone can read aloud.',
    'When my head feels crowded, I walk outside for two minutes.',
  ],
  temporal_processing: [
    'I notice shadows shifting and guess the time of day.',
    'When someone says “soon,” I ask roughly how many minutes.',
    'If I must wake early, I prepare clothes the night before.',
    'When cooking, I track time with songs I know by length.',
    'I feel when a season is turning before the calendar says so.',
    'When waiting feels long, I check the sun or a clock if I can.',
    'If a child asks “how long,” I compare to a known chore.',
    'When planning travel, I add extra time for rough roads.',
    'I remember recurring market days better than dates on paper.',
    'When dusk arrives, I start closing tasks without being told.',
    'If I promise “tomorrow,” I tie it to morning light in my mind.',
    'When music speeds up, I match my steps without thinking.',
    'I feel hunger at roughly the same hours most days.',
    'When a meeting runs late, I shift later jobs in my head.',
    'If night work is needed, I nap first when possible.',
    'When seasons affect planting, I watch neighbors’ fields.',
    'I estimate distance by how long my feet ache.',
    'When tides matter, I ask locals instead of guessing.',
    'If a child naps, I use that window for quiet work.',
    'When bells or calls mark hours, I sync my pace to them.',
    'I notice when my body wants rest before my mind admits it.',
    'When time zones confuse me, I anchor to one meal.',
    'If a task takes longer once, I plan longer next time.',
    'When stars appear, I know evening chores should finish.',
    'When roosters call, I treat it as a soft alarm.',
  ],
  self_regulation: [
    'When anger rises, I breathe before I speak.',
    'If I want to quit a hard job, I promise myself only five more minutes.',
    'When sweets are nearby, I can take one and step away.',
    'If someone insults me, I leave the place before I answer harshly.',
    'When tired, I still finish one small duty I started.',
    'When laughter bursts out, I can lower my voice if needed.',
    'If I fail once, I try again with a smaller step.',
    'When pain appears, I notice it without deciding the whole day is bad.',
    'If I speak too loud, I soften when I see faces wince.',
    'When envy appears, I name one thing I already have.',
    'If a habit hurts me, I change the cue, not only the will.',
    'When shame visits, I tell one trusted person.',
    'If I spill something, I clean before blaming anyone.',
    'When tempted to lie small, I tell a plain truth instead.',
    'If children copy my tone, I slow my speech on purpose.',
    'When I want to buy what I cannot afford, I walk away first.',
    'If news scares me, I check one fact before I spread it.',
    'When I interrupt, I apologize and yield the floor.',
    'If I feel faint, I sit and drink before standing proud.',
    'When pride blocks an apology, I say sorry anyway.',
    'If I oversleep, I skip blame and start the next useful task.',
    'When online chatter pulls me, I set the device face down.',
    'If I gossip, I stop mid-sentence when I notice.',
    'When muscles beg to stop, I stretch once then decide.',
    'If I break a promise, I make a smaller promise I can keep.',
  ],
  motivation: [
    'When a task helps people I know, I push through tiredness.',
    'If the goal feels far, I still enjoy the first visible step.',
    'When praise is rare, I keep going if the work itself matters.',
    'If I promised quietly, I treat it like a public vow.',
    'When learning helps my family, I return to it after breaks.',
    'If boredom hits, I change the method, not always the goal.',
    'When small wins appear, I notice them aloud.',
    'If fear says stop, I shrink the task until I can start.',
    'When a friend counts on me, I rise earlier.',
    'If the sun is hot, I still move if someone waits.',
    'When tools are poor, I improvise instead of waiting forever.',
    'If my body is weak, I do one gentle part of the job.',
    'When songs play, rhythm helps me repeat dull work.',
    'If others rest, I may still finish my slice if time is short.',
    'When a deadline is real, I front-load the hardest piece.',
    'If reward is unclear, I tie the job to care for someone.',
    'When mockery stings, I use it as fuel only briefly, then cool down.',
    'If luck fails, I try a different path the same day.',
    'When night comes, I stop dangerous work even if eager.',
    'If hope dips, I remember one past time I persisted.',
    'When elders watch, I show steady effort, not only speed.',
    'If money is small, I still polish what I sell.',
    'When competition rises, I focus on my own line.',
    'If praise floods, I stay polite and keep standards.',
    'When the task is lonely, I speak kindly to myself.',
  ],
};
